name: PEP 8 Style Check

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Code with flake8
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run flake8
      run: |
        flake8 .
      continue-on-error: false