name: Execute automation test cases manually
on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Path or file to be executed. If you want to run all just use .'
        default: '.'
        required: true
      environment:
        default: 'qa'
        description: 'Environment to execute the flow.'
        required: false
      tags:
        default: ''
        description: 'Tags to execute the specific set of test cases. -i for include -e to exclude.'
        required: false
jobs:
  create-env:
    name: ${{ matrix.os }} 
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
        
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v4
        
      - name: create conda environment.
        uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          auto-activate-base: false
          activate-environment: testing-framework
          environment-file: testing_framework.yaml
      
      - name: Install playwright.
        run: |
          playwright install


      - name: Get env variables from secrets according to your selection
        run: |
          echo ${{ secrets.CONFIG_${{ github.event.inputs.environment }} }} > config/config_${{ github.event.inputs.environment }}.env
        
      - name: Execute Smoke Tests.
        run: |
          pytest -v tests --headless -m smoke --env=${{ github.event.inputs.environment }}
        continue-on-error: false
      
      - name: Remove the config file.
        run: |  
          rm -f config/config_${{ github.event.inputs.environment }}.env

      - name: Save artifacts.
        uses: actions/upload-artifact@v4
        with:
          name: tests-results
          path: results