name: Code Style Check

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Code with flake8 and pydocstyle
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install flake8 and pydocstyle
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle pydocstyle

    - name: Run flake8
      run: |
        pycodestyle .
      continue-on-error: false

    - name: Run pydocstyle
      run: |
        pydocstyle .
      continue-on-error: false